grafana:
  enabled: true
  adminPassword: admin
  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true
    ## Annotations for Grafana Ingress
    ##
    annotations:
      kubernetes.io/ingress.allow-http: "true"
      kubernetes.io/ingress.class: nginx
    hosts:
      - hostname.xyz.com
    path: /grafana/
    pathType: ImplementationSpecific
  ## Grafana's primary configuration
  ## NOTE: values in map will be converted to ini format
  ## ref: http://docs.grafana.org/installation/configuration/
  ##
  grafana.ini:
    server:
      domain: hostname.xyz.com
      root_url: http://hostname.xyz.com/grafana/
      serve_from_sub_path: true
